apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: cardetection-mm
  namespace: modelmesh-serving
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
    serving.kserve.io/secretKey: localMinIO
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      runtime: triton-2.x
      storageUri: s3://modelmesh-example-models/cardetect/yolov8n_car