apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: multi-worker
  namespace: distributed-training
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: 6666688889/distributed_training:0.0.13
              volumeMounts:
                - mountPath: /train
                  name: training
                  readOnly: true
          volumes:
            - name: training
              persistentVolumeClaim:
                claimName: mwt-volume
                readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mwt-volume
  namespace: distributed-training
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi