pipeline {
    agent any

    options{
        buildDiscarder(logRotator(numToKeepStr: '5', daysToKeepStr: '5'))
        timestamps()
    }

    environment{
        registry = '666688889/distributed_training'
        registryCredential = 'dockerhub'      
    }

    stages {
        stage('Initialize') {
            steps {
                script {
                    def dockerHome = tool name: 'myDocker', type: 'com.cloudbees.jenkins.plugins.customtools.CustomTool'
                    env.PATH = "${dockerHome}/bin:${env.PATH}"
                }
            }
        }   
        stage('Build') {
            steps {
                script {
                    echo 'Building image for deployment..'
                    dockerImage = docker.build registry + ":$BUILD_NUMBER" 
                    echo 'Pushing image to dockerhub..'
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
              
