apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: onnx
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      storage:
        key: localMinIO
        path: onnx/1/best.onnx